### ISSUE TITLE
Crashing on Startup.

### ISSUE THREAD

**Issue by PromajaFighter** [kpzip/Enchanting-Tweaks#11]
Version:
1.20.2-1.2.2
Fabric Api Version:
0.9.0.0+ 1.20.2
Log: 
https://mclo.gs/Nr2zVRC

It just crashes on startup and I dont know how to fix it.
Maybe you can fix it.

**Comment by kpzip** [comment]
Seems like it should be an easy fix, ill look into it later today.

**Comment by kpzip** [comment]
I looked into this issue, and It appears that this only happens with fabric loader version 0.14.23 and later. I will get around to releasing a compatibility fix at some point, but for now try downgrading to fabric loader version 0.14.22 for a temporary fix.

**Comment by Hng-Vit** [comment]
> I looked into this issue, and It appears that this only happens with fabric loader version 0.14.23 and later. I will get around to releasing a compatibility fix at some point, but for now try downgrading to fabric loader version 0.14.22 for a temporary fix.

waiting for the fix man ✌️

**Comment by Shadowolf50146** [comment]
Hi! I have the same problem but it happens on 0.14.22 too, and any older versions of fabric wont work (mod compatability withen my mass of performance and qol mods)

I load into the menu as normal, but as soon as i load into ANY world, new or premade, it crashes.

I'll send the fabric 0.14.22 logs to hopefully help.

MC 1.20.2
fabric loader 0.14.22
fabric api 0.90.7+1.20.2

https://mclo.gs/U3cQeVj

**Comment by kpzip** [comment]
This issue seems to be more pervasive than I thought...
Ill aim to release the fix tomorrow.

**Comment by kpzip** [comment]
Fixed in 1.2.3

**Comment by kpzip** [comment]
Fixed in 1.2.3
