### ISSUE TITLE
Ability to Change Tooltip Keybinds

### ISSUE THREAD

**Issue by QuackingDuckz** [kpzip/Enchanting-Tweaks#13]
Hey, I was wondering if there is a way to adjust what keybind you hold to have the different details show up?

I could probably dig around in the files to do it, but im not super great at reading code so it would take a long time.

Thanks!

**Comment by kpzip** [comment]
This is actually a feature I've been thinking about, ill work on adding it when I get some time.

**Comment by kpzip** [comment]
Added in 1.2.4 [download](https://modrinth.com/mod/enchanting-tweaks/version/1.2.4)
