### ISSUE TITLE
Upload 1.20.4 release to CurseForge?

### ISSUE THREAD

**Issue by chimericdream** [kpzip/Enchanting-Tweaks#20]
I see that the mod has been updated to 1.20.4, but for whatever reason that one hasn't been uploaded to the CF page yet. Is there an ETA on doing that?

Thanks!

**Comment by kpzip** [comment]
I believe it has, however it was not marked as being for Minecraft 1.20.4. I fixed it, and the file is available [here](https://www.curseforge.com/minecraft/mc-mods/enchanting-tweaker/files/4944702).
