### ISSUE TITLE
[Suggestion] Allow enchantment descriptions to be toggleable

### ISSUE THREAD

**Issue by TrueDevron** [kpzip/Enchanting-Tweaks#3]
As the title suggests, I would like to see the ability to toggle enchantment descriptions

**Comment by kpzip** [comment]
If you wouldn't mind clarifying, you mean toggling them in the sense that they would be shown without holding shift?

**Comment by chonkyman** [comment]
> If you wouldn't mind clarifying, you mean toggling them in the sense that they would be shown without holding shift?

No, I think they mean being able to disable the "Hold Shift, Hold Alt, etc." entirely in the config

**Comment by chonkyman** [comment]
Any updates? @kpzip

**Comment by kpzip** [comment]
The feature is finished, still haven't gotten around to doing comprehensive tests though

**Comment by kpzip** [comment]
The feature has been implemented and is available in v1.2.2.
